version: "3"
services:
  database:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: ${DATABASE}
    container_name: "${COMPOSE_PROJECT_NAME}-database"
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    expose:
      - 3306
      - 33060
  wordpress:
    image: ${WORDPRESS}
    container_name: "${COMPOSE_PROJECT_NAME}-html"
    volumes:
      - ./www:/var/www/html
    ports:
      - ${HOST_MACHINE_UNSECURE_HOST_PORT}:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=database
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
  phpmyadmin:
    image: ${PHPMYADMIN}
    container_name: "${COMPOSE_PROJECT_NAME}-phpmyadmin"
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      UPLOAD_LIMIT: ${UPLOAD_LIMIT}
      MEMORY_LIMIT: ${MEMORY_LIMIT}
    ports:
      - "${HOST_MACHINE_PMA_PORT}:80"
      - "${HOST_MACHINE_PMA_SECURE_PORT}:443"
    volumes:
      - /sessions
      - ./config/pma/config.inc.php:/etc/phpmyadmin/config.inc.php
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
  # redis:
  #   container_name: "${COMPOSE_PROJECT_NAME}-redis"
  #   image: redis:latest
  #   ports:
  #     - "127.0.0.1:${HOST_MACHINE_REDIS_PORT}:6379"